### ISSUE TITLE
Wrong volume calcs for RD-108 mount

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ROTanks#10]
Many mounts add some fuel volume; some make sense, but RD-108 doesn't. RD-107 also looks dubious, there's probably others.

In the 108's case, it feels like the full height of the mount is treated as usable tank, when it's mostly just a fancy shroud.

Compare:

![rd108](https://cdn.discordapp.com/attachments/319857228905447436/610187325057531905/Screen_Shot_2019-08-11_at_3.06.16_PM.png)

![Shroud(XLong)](https://cdn.discordapp.com/attachments/319857228905447436/610187700883947530/Screen_Shot_2019-08-11_at_3.07.53_PM.png)

**Comment by lpgagnon** [comment]
Also worth noting that both the PAW 'Total Length' value and RP-0's Tooling window ignore the mount's length altogether; for the attached picture, it shows 0.4m (the shortest a 2.5m tank can be). With that length it should hold ~2kL, but holds 15.9kL.

**Comment by pap1723** [comment]
Are you considering that the tank doesn't go all the way to the bottom and isn't a true cylinder, but instead is a half dome? Does that still make it wrong?

**Comment by lpgagnon** [comment]
I don't understand the question. The problem isn't that capacity is too low, it's that it's too high. The rd108 shroud is treated like a 4m-long tank instead of a 4m-long hollow tube

**Comment by pap1723** [comment]
Fixed with https://github.com/KSP-RO/ROTanks/commit/225fc13414afbff3e601cf326e87b9db60604ae7
