### ISSUE TITLE
RD-107 mount is rotated 90 degrees

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ROTanks#11]
The rd-107 mount is one of the few non-symmetrical ones; since there are also non-symmetrical nosecones, mounts and noses should be rotated the same way. Currently, they're not, so we get a weird side-saddle effect.

![](https://cdn.discordapp.com/attachments/319857228905447436/611970286711210019/Screen_Shot_2019-08-16_at_1.07.51_PM.png)

**Comment by lpgagnon** [comment]
However the mount is rotated correctly when used with the booster tanks... the ROT_MODEL has an explicit -90degree rotation; I'm guessing its there to compensate for something the booster tank does, and has an unintended side-effect on the normal tank

**Comment by lpgagnon** [comment]
Setting a booster tank's Mount to one of the asymmetrical nosecones also ends up with a rotated-90-degrees effect. (doing the same on a normal tank... gives a 180-degree effect, nose pointing outwards instead of inwards)

**Comment by pap1723** [comment]
Fixed with https://github.com/KSP-RO/ROTanks/commit/a8d918cabebffc47b960a87f1718dd7e86feb717
