### ISSUE TITLE
Modular Tank Size: Infinite Density Bug

### ISSUE THREAD

**Issue by oNodrak** [KSP-RO/ROTanks#15]
There is a bug with the new Modular Tanks that allows infinite fuel in any size tank.

The process:  

1: Add a Tank, increase the utilization to max (they start slightly under max).  
2: Save the Craft  
3: Load the Craft, the tank will have reset Utilization %, but not fuel volume.  
4: Increase Utilization to max.
5: Repeat Steps 2-4.

E: Some additional testing has concluded that the issue is related to the Tank-II upgrade of the Modular Tank, as the tank will reset to 88% instead of 92%.

**Comment by lpgagnon** [comment]
realfuels bug; fixed in master, hasn't been released yet.

**Comment by oNodrak** [comment]
Thanks, I will check it out
