### ISSUE TITLE
Could we get shielded tanks?

### ISSUE THREAD

**Issue by Its-Just-Luci** [KSP-RO/ROTanks#18]
Procedural parts is glitchy and a mess in 1.7.3 but the only things that makes me think twice about deleting it are the polygon tanks and the shielded tanks, more the latter than the former.

**Comment by pap1723** [comment]
For Procedural Parts, make sure you download the one from the KSP-RO repo. There is one in releases.

As far as structural tanks, that should definitely be something I can add. Most likely it won't be until I get the new style of tank selection working properly.

**Comment by DRVeyl** [comment]
Different tank configurations and properties has moved into RO.  ROT is more about providing the dynamic shapes & volumes for those tanks, but doesn't/won't care about the part specs [like thermal controls].
