### ISSUE TITLE
Dome-Framed-M invisible mesh

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-RO/ROTanks#2]
I mentioned that on Discord, now I place it here.

See:
![screenshot_2019-06-26--01-58-00](https://user-images.githubusercontent.com/29145213/60141449-dc281580-97b5-11e9-99ba-fea052bbce5c.png)

**Comment by nepphhh** [comment]
Seconded, the model is invisible for either mounts or noses.

**Comment by pap1723** [comment]
Fixed with #12
