### ISSUE TITLE
Incorrect  nodes on modular tanks

### ISSUE THREAD

**Issue by EastwindCC** [KSP-RO/ROTanks#21]
A moudular tank with specific noses or mounts has incorrect nodes.
For example,the top node of 1:3-short-nose is 
attN= top,Null_0_0|1.13333333|0_0|-1|0_0|1.13333333|0_0|-1|0.

**Comment by DRVeyl** [comment]
Can you clarify what the attachment node position _should_ be?

**Comment by EastwindCC** [comment]
Node position is correct. With some noses,the top node can only be attached from bottom.
It shoule be
attN= top,Null_0_0|1.13333333|0_0|-1|0_0|1.13333333|0_0|1|0.

**Comment by DRVeyl** [comment]
Ref: https://github.com/KSP-RO/ROTanks/pull/22
