### ISSUE TITLE
Code for Calculating Volume

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/ROTanks#26]
With @lpgagnon figuring out the parts with different upper and lowerDiameters having incorrect volume ratios added, there is definitely a code issue somewhere inside there.

**Comment by DRVeyl** [comment]
Think this is fixed in <https://github.com/KSP-RO/ROLibrary/commit/eeec7f6a04ae62be9e1fdbdf3fd8559fc69059bf>

Whee, fun tracking bug reports in these separate repos but getting to fix everything code in ROLib! ;)
