### ISSUE TITLE
ROTanks decoupler problems

### ISSUE THREAD

**Issue by nepphhh** [KSP-RO/ROTanks#28]
I attach two WACs, identical in every way besides that one uses a pp decoupler & the other a ROTanks decoupler between the Tim & WAC. 

Required mods: RO, RP-1, Proc Parts, RealChutes, ROEngines, B9 Wings, ROTanks.

_I don't have problems_
![image](https://user-images.githubusercontent.com/4913409/77219415-f8ba6980-6b0b-11ea-96e7-e2793de06027.png)

_I have problems_
![image](https://user-images.githubusercontent.com/4913409/77219421-01ab3b00-6b0c-11ea-8f33-c20ad1412d07.png)

Staging is a standard hot-staging affair. The PP decoupler version can be reliably staged by hand, even if it's not hot-staged & the WAC Bee is lit in the air after Tim burnout.

The ROTanks decoupler version has ullage issues very single time, even when hotstaged, even when hotstaged through kOS.

This will be crippling to new players trying to use the ROTanks decoupler & hints at potentially major drag issues.

(Also, the ROTanks decoupler costs twice as much untooled than the comparable PP decoupler of same diameter)

**Comment by nepphhh** [comment]
[VAB.zip](https://github.com/KSP-RO/ROTanks/files/4362446/VAB.zip)

**Comment by DRVeyl** [comment]
Does this still apply after our investigation with FAR?

**Comment by nepphhh** [comment]
Very very unlikely. Will test with new FAR binaries when I am able.
