### ISSUE TITLE
ROTanks make clamped vessels spawn too high

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ROTanks#31]
Apparently it's ROTanks that's confusing ksp into spawning clamped vessels too high above the launchpad.
This guy is consistently spawning like this:
https://cdn.discordapp.com/attachments/663102368887472156/716029251979182089/Screen_Shot_2020-05-29_at_16.44.13.png

[](https://cdn.discordapp.com/attachments/663102368887472156/716029251979182089/Screen_Shot_2020-05-29_at_16.44.13.png)

Replacing rotank by proctank lets it spawn just above the ground
Doesn't seem to matter if the clamps are attached to the tank or something else, nor if the tank is above or below the something else
Stacking extra tanks doesn't seem to increase the offset
In fact the offset appears to be max(all rotank heights)

**Comment by rsparkyc** [comment]
I was wondering what mod was causing this. Now I know.

**Comment by DRVeyl** [comment]
Fixed by <https://github.com/KSP-RO/ROLibrary/commit/ade6d0d8c73a5590abed066520379d65b3c933ef>
