### ISSUE TITLE
Can we have internal tanks?

### ISSUE THREAD

**Issue by JustCommitRandomness** [KSP-RO/ROTanks#33]
These would be tanks for putting inside things. They would be like separate structure tanks, but without the separate structure. I|'d expect them to be cheaper than separate structure tanks and lighter than balloon tanks -- possibly even zero base mass, allowing RealFuels' internal tank mass to be the tank mass.

It may make sense for the tanks to be radially attachable only, to partially enforce the requirement for there to be a structure for it to be "part" of.

It may make sense to not allow radial attachment of anything to the tanks.

Ideally there should be options such as insulation.

This would allow explicit placement of tanks within structural fuselage or service bays &c.

Ideally the external volume should be available. This would facilitate tank-in-tank designs (extending RealFuels to have an internal tankage tank or reserved tank volumes that could be added to a tank would be the other part of that)

**Comment by DRVeyl** [comment]
This should be in the general RO GitHub. ROTanks doesn't implement any tank definitions. It's generally a model manipulation system.
