### ISSUE TITLE
Tanks appear invisible

### ISSUE THREAD

**Issue by kyleander** [KSP-RO/ROTanks#39]
The modular tanks from ROTanks appear invisible in VAB/SPH and do not show up once clicked.

The game version is KSP 1.10.1 running RSS/RO.

[KSP.zip](https://github.com/KSP-RO/ROTanks/files/5601573/KSP.zip)

**Comment by FlightXKSP** [comment]
What was the conflict. What mod was conflicting. I seem to have the same problem.

**Comment by teeshq** [comment]
Have same issue what mods which causing ??

**Comment by pap1723** [comment]
This mens you likely downloaded the master of ROLib
