### ISSUE TITLE
Normal/texture map request: MLI foil and Juno/Thor-Able roll stripe.

### ISSUE THREAD

**Issue by nepphhh** [KSP-RO/ROTanks#4]
The "gold" normal map is nice, but something more like either of the default folded foil textures from proc tanks would be fantastic. 
![image](https://user-images.githubusercontent.com/4913409/60546995-9a82f780-9cec-11e9-8722-c4bdbe829ef1.png)

Additionally, the roll stripe (?) found on Juno/Jupiter-C (top), Thor-Able, and whatever this saturn-esque stripe is would be awesome for early US rockets. 
![image](https://user-images.githubusercontent.com/4913409/60547137-f8174400-9cec-11e9-8b32-b7683e7cb841.png)

**Comment by DRVeyl** [comment]
You've picked up some experience with this recently.  Looks like you'd want to make edits to eg: https://github.com/KSP-RO/ROTanks/blob/master/GameData/ROTanks/Data/TextureSets/TextureSets-Spheres.cfg   for the spherical tanks.  Also consider the radial ones.

**Comment by nepphhh** [comment]
I'll take a look at it, although the complexity of the ROTanks model means I believe I'll have to unwrap the UV map which is... something I haven't learned to do yet. I'm going to close this for now, tupp offers an alternate solution to this "problem"
