### ISSUE TITLE
Ring Decoupler mass scales differently than proc decoupler

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ROTanks#40]
min-height 1m procparts decoupler: 26kg
min-height 1m ROTanks Ring Decoupler: 15kg

min-height 2m procparts decoupler: 104kg
min-height 1m ROTanks Ring Decoupler: 121kg

(these are numbers for RO, which I think plays a role in how procparts mass behaves)

No idea which is "more correct", I'm guessing there's not a lot of realism that goes into either. But the discrepancy is counterintuitive, and procparts was there first, so presumably ROTanks should go along. 

(Proc Fairings Hollow Interstage Ring is out of step with both, but that gets into apples & oranges)

**Comment by DRVeyl** [comment]
Fixed by https://github.com/KSP-RO/ROLibrary/commit/85f74aa9faa2b2c87e260a8786bfde53fd51a587
