### ISSUE TITLE
Toroidal/radial tank recoloring issues in 1.10/1.11

### ISSUE THREAD

**Issue by StonesmileGit** [KSP-RO/ROTanks#43]
Settings in recoloring GUI: First color is the normal color, second is 'blue paint' and third is 'red paint'

Effected parts are Toroidal tank and Radial tank, but not spherical tank
![image](https://user-images.githubusercontent.com/62522391/110367439-f23c3f00-8047-11eb-9253-963b8418ebcd.png)

**Comment by al2me6** [comment]
Cause determined - Squad revamped the models that these parts used.

**Comment by pap1723** [comment]
Fixed with https://github.com/KSP-RO/ROTanks/commit/8be84e0bacf8ca97aa5b9212fcf4f9ad2e543dd0
