### ISSUE TITLE
RD-107 mount is rotated 90°

### ISSUE THREAD

**Issue by leudaimon** [KSP-RO/ROTanks#44]
Pretty much what it says in the title. The RD-107 mount is rotated in the modular tank (at least in the Integral part). Makes it very difficult to use. Given that's not the case in the booster tank part, it should be an easy fix.

**Comment by pap1723** [comment]
Strangely, it works properly on the Booster tank as you mentioned...turns out the fix is not that easy. Hmmm.

**Comment by pap1723** [comment]
Fixed with ROLib which now allows independent rotation of Noses and Mounts.
