### ISSUE TITLE
Modular tanks not showing up.

### ISSUE THREAD

**Issue by FlightXKSP** [KSP-RO/ROTanks#45]
I followed carnasas tutorial to install Ro/Rss. All tho when I don't see the modular tanks. I used ckan and I run on 1.8.1.

**Comment by leudaimon** [comment]
Did you install ROTanks? Modular tanks are part of ROTanks, not of a "vanilla" RO install.

**Comment by FlightXKSP** [comment]
Yes I did install Ro tanks.

**Comment by FlightXKSP** [comment]
I can't see any Rotank.

**Comment by StonesmileGit** [comment]
With latest release of ROTanks, you need master of RO, however due to a current bug on master, I would recommend getting Master from 3 commits ago (as of writing); https://github.com/KSP-RO/RealismOverhaul/archive/77b0a7feb8e2f2373b7451574830686737d50b31.zip

**Comment by DRVeyl** [comment]
I error'd.  I was committing changes to ROTanks and RO master that were paired together.  The ROTanks parts on current release but without RO master [as of the date of the release] will be flagged as Non-RO.  The parts are still there, but they're hidden if you also have the NoNonRO folder.  We're closing in on an RO release, so this problem should resolve soon.  Until then, @StonesmileGit  has posted the workaround.

**Comment by DRVeyl** [comment]
This was resolved with the release of RO.
