### ISSUE TITLE
ROTanks don't snap to node on radially attached objects

### ISSUE THREAD

**Issue by daantimmer** [KSP-RO/ROTanks#46]
ROTanks (normal tanks, booster tank, toroidal tank and spherical tank) don't attach to nodes that are radially attached. See video below for exampled details:
https://gfycat.com/anxiousselfassuredamericanalligator

The only way to get them to snap to node is by first trying to radially attach them while trying to align the nodes. Also shown in the example.

**Comment by daantimmer** [comment]
KSP 1.10.1
ROTanks v2.3

**Comment by daantimmer** [comment]
Probe cores provided by ROTanks face the same issue

**Comment by pap1723** [comment]
Fixed with newest release of ROTanks and ROLib
