### ISSUE TITLE
ROTank models not showing in game

### ISSUE THREAD

**Issue by si2504** [KSP-RO/ROTanks#47]
ROTanks installed, dependencies installed but no models nor thumbs are showing. For example, I see the tab for procedural probe in VAB, but the thumb is blank and if i click on it, the model is invisible, only the attachment nodes can be seen.

**Comment by DRVeyl** [comment]
Get ROLib from the release.  Not from the master branch, which does not contain the dll.

**Comment by si2504** [comment]
Thank you kind sir!
