### ISSUE TITLE
Math seems incorrect on tank sizing

### ISSUE THREAD

**Issue by rsparkyc** [KSP-RO/ROTanks#5]
from the #general room is discord:
I'm just looking at the math of the spherical tank, and it seems like it holds more than theoretically possible, and the radial version of it is way low.  A 1 meter diameter sphere has a volume about 0.523 cubic meters, so that's 523 liters.  The spherical tank says it could hold 586 liters, and that's not even taking into account skin thickness.  The procedural tanks' numbers seem much more inline: `532 * 0.92 (utilization percentage) = 481`, and the normal procedural tank says 482, so that looks right.  Looking at just the "modular tank", a 1 meter cylinder at 100% says it holds 556L, but I think the math `(pi r^2 x h)` would have that at closer to 785 liters.

Here is the radial spherical tank: volume seems way too low
![image](https://user-images.githubusercontent.com/2042290/62058820-0a9f7300-b1f0-11e9-9060-df3ef83b5642.png)

And the standard spherical tank: volume seems theoretically impossible
![image](https://user-images.githubusercontent.com/2042290/62058805-02473800-b1f0-11e9-8abd-8040b4ae440d.png)

**Comment by rsparkyc** [comment]
Attached is an image showing the cylindrical tanks as well as the spherical ones
![image](https://user-images.githubusercontent.com/2042290/62098323-d19ae900-b257-11e9-8977-6ad162bbb105.png)

**Comment by rsparkyc** [comment]
I'm guessing this comes from the volume set in `ROT-RadialTank.cfg` being set to 128, but being set to 504.238 in `ROT-SphericalTank.cfg`.  If the "base" volumes are being calculated from there instead of actually being computed from the shape of the object, I'm not quite sure how well it will scale as you change the size of the shape (especially the radial tank, which can be elongated into a pill.  Ideally, I'd think you'd completely ignore those values, and just compute it from the dimensions you've selected in the PAW.

**Comment by rsparkyc** [comment]
Another update: It looks like the the SphericalTank is setting its initial volume when you place the part to 504, and not applying the default utilization percentage of 86%.  When change tank types or drag the utilization slider, it does not try to re-calculate the actual potential volume of the part.  However, if you resize the tank and then go back (for instance: 1.0 -> 1.1 -> 1.0), the volume looks more inline with what it should be, so perhaps a big part of the fix it just making sure we run the volume code when the part is dropped into the editor instead of just using the value from the config.

**Comment by pap1723** [comment]
I can promise you the volumes for the cylindrical tanks in ROTanks are
much, much, much more accurate than the ones in Procedural Parts. The
ROTanks are actually constructed of 3 parts. The core, nose and mount. The
nose and mount default to cylinder pressure caps. The calculated volume for
those tanks is taken into account. When you change the nose or mount type,
the additional space is accounted for properly as well.

Procedural Parts on the other hand consider every single part in the tank
as having volume. Realistically, you could not construct a pressure vessel
for a tank without having a rounded dome on it.

**Comment by MikeOnTea** [comment]
The spherical or the radial tank? Those don't quite seem to agree what volume is accurate. ;)

**Comment by pap1723** [comment]
Damnit, the cylinders I meant, sorry. The basic modular ones.

I do not know why / if the volume is wrong on the Cylinder and Radial. I
thought I had calculated them properly. But I would guess I might not have.

**Comment by rsparkyc** [comment]
ok, that totally makes sense.  I guess we could expect the cylindrical tanks to be more inline with the pill shape (though they should hold slightly more since it's not just a half-sphere on the top and bottom, but instead more of a dome shape).  I adjusted the volume of the radial tank to be more inline with what I thought it should be, and it comes in as holding a fraction less than a basic tank of the same size/configuration.  It also matches what I felt a spherical tank should be.  I'll submit a PR.

**Comment by rsparkyc** [comment]
I also tried scaling up a 1.0x-Kero tank to match a 1.5x-Kero tank, and noticed that even though they're the same size, the 1.5x holds more.  This would make sense, because when you use the V.ScaleAdj, it's probably scaling both the inner cylinder AND the domes, rather than just stretching the cylindrical part of the tank and leaving the domes the same volume.
