### ISSUE TITLE
Attaching two tanks from their bottom nodes crashes the game

### ISSUE THREAD

**Issue by JackIt999** [KSP-RO/ROTanks#52]
When I attach two modular fuel tanks together via their bottom nodes in the VAB, the game freezes and crashes. KSP does not even give me a crash report.

**Comment by pap1723** [comment]
Like if you flip a 2nd tank over and attach it to a previously placed tank?

**Comment by JackIt999** [comment]
Exactly like that. What I did exactly was I placed down a command pod from another mod, and attached a tank to it. I then duplicated that tank (by ctrl+z), flipped it, and as soon as I attached it, the game froze and crashed with no crash message.

**Comment by JackIt999** [comment]
I have made a new discovery! The issue appears to happen ONLY when it is connected to the command pod. I am beyond perplexed.

**Comment by JackIt999** [comment]
I have made another discovery - it only crashes if the tank has a mount assigned to it. It does not matter if it is the top or bottom node

**Comment by pap1723** [comment]
Fixed with newest release of ROTanks and ROLib
