### ISSUE TITLE
Latest version breaks old crafts whith Ring Decoupler

### ISSUE THREAD

**Issue by Tagir-1** [KSP-RO/ROTanks#60]
The game says "craft_name is missing part ROT-RingDecoupler" when loading the save. I've looked through files and configs and ROT-RingDecoupler.cfg uses ROTanks/Assets/EmptyProxyModel as a model. ROTanks 2.3 has this file,  ROTanks 2.4 doesn't.

So I used EmptyProxyModel.mu from 2.3 and everything works now

**Comment by pap1723** [comment]
Fixed with new release! Thank you!
