### ISSUE TITLE
Cannot manage to make the Atlas skirt not to explode everything when decoupling 

### ISSUE THREAD

**Issue by Bob-Kelso** [KSP-RO/ROTanks#62]
I tested lots of ways to make the decoupling works on the Atlas skirt when mounted to the Atlas tank with diverse mounting options but everytime i stage it just blows no matter the mount or adding a custom procedural tank. I tried with LR 105 and two LR89 from RO Engines

If you have any hint on how to make it work properly^^.

thanks for the work you've made so far btw, it's just awesome

**Comment by bofhgr** [comment]
Not part of the devs but it worked like a charm for me. All i did was make a 3m diameter, added the 2:1 bottom mount and attached the 105 there, then the 101 verniers on the radial sides, pick up the decoupler, make it 3m diameter, slap it there and add the 89s. Made an action bound to '1' on the action settings to manually shutdown the 89s before the skirt separation. So far 3/3 nominal launches, great addition in ro!

**Comment by Bob-Kelso** [comment]
Indeed, it works fine with a long 2:1 bottom mount :). Thanks for the advice

**Comment by adamisafk** [comment]
Having the same issue, what did you mean by "2:1 bottom mount"? @Bob-Kelso @bofhgr

**Comment by adamisafk** [comment]
Oh I see it, thanks!
