### ISSUE TITLE
BUG: Modular Tank (Conventional Structure) appears on the rocket as (Separate Structure)

### ISSUE THREAD

**Issue by dgeastman** [KSP-RO/ROTanks#64]
Attempting to build a first-node rocket, I selected Modular Tank (Conventional Structure) from the parts bar. On the rocket however, it shows as (Separate Structure) in the PAW, with no ability to change it, and KCT will not allow the rocket to be built as that tech is not unlocked.

**Comment by NathanKell** [comment]
Probably due to https://github.com/KSP-RO/RP-0/pull/1469 -- @lpgagnon ?

**Comment by lpgagnon** [comment]
I don't see how, conventional/sep is the one family _not_ touched by that PR

**Comment by dgeastman** [comment]
I think this is even worse than at first blush, it's both the Modular and Procedural tanks, but unlike the modulars, procedural tanks actually get built as separate, even though I don't have that tech.
