### ISSUE TITLE
R-7 style booster tanks have crossfeed and built in decouplers.

### ISSUE THREAD

**Issue by madjedi22** [KSP-RO/ROTanks#67]
R-7 booster tanks have crossfeed and built in decouplers allowing for drop tanks and asparagus staging.

**Comment by StonesmileGit** [comment]
The decouplers are intentional, as that is how they are used on real rockets (All R7 variants, inluding Soyuz) however the crossfeed should probably be removed. (I have looked at it a little some time ago, but didn't get anything done)

**Comment by StonesmileGit** [comment]
The main problem is that if you disable crossfeed, then engines can't use the fuel

**Comment by pap1723** [comment]
Fixed in newest release
