### ISSUE TITLE
ROTanks 2.6.1 - Problem with misssing NewTank parts in KSP 1.10.x

### ISSUE THREAD

**Issue by kretze** [KSP-RO/ROTanks#74]
ROTanks 2.6.1 - Problem with misssing NewTank parts in KSP 1.10.x

I have the problem that after the update to 2.6.1 more than half of my ships are no longer usable because parts are missing.
ROT-GenericTank-Balloon
ROT-GenericTank-ServiceModule
ROT-NewTanks

The new tank parts were outsourced to RO. RO 14.12 is not compatible with 1.10.x, so ROTanks 2.6.1 is not fully compatible with KSP 1.10.x.

Actually, a dependency on ROTank 2.6.1 and RO 14.12 or an information advising that in 1.10.x and ROTanks 2.6.1 some ships might not be usable.

**Comment by DRVeyl** [comment]
Oops, that's correct.  ROT's latest needs to be marked 1.12+ only.

**Comment by DRVeyl** [comment]
ROTanks release package has been updated, and CKAN has completed reindexing and now identifies ROT 2.6.1 as requiring KSP 1.12.
