### ISSUE TITLE
Spherical tank needs to be resized in the PAW before having proper volume

### ISSUE THREAD

**Issue by rsparkyc** [KSP-RO/ROTanks#8]
It looks like the the SphericalTank is setting its initial volume when you place the part directly from the config files, and not applying the default utilization percentage of 86%. When change tank types or drag the utilization slider, it does not try to re-calculate the actual potential volume of the part. However, if you resize the tank and then go back (for instance: 1.0 -> 1.1 -> 1.0), the volume looks more inline with what it should be, so perhaps a big part of the fix it just making sure we run the volume code when the part is dropped into the editor instead of just using the value from the config.

This was discovered in #5, but that issue will be closed when #7 is merged

**Comment by DRVeyl** [comment]
If this hadn't been addressed before, I believe it is fixed in https://github.com/KSP-RO/ROLibrary/pull/3 as part of the logic migration to ROLib and the rework of part initializations.
