### ISSUE TITLE
ROT Booster tank volume too low

### ISSUE THREAD

**Issue by Capkirk123** [KSP-RO/ROTanks#87]
The ROT booster tank volume is significantly lower than it should be. According to astronautix (yeah, I know), a fully fueled 8K71 booster should mass 43.1 tons, and burn for roughly 2 minutes. 
An ROT Booster tank, set to aluminum-stringer, booster-3 with a base diameter of 2.68 meters and vscale of 1.02 for a height of 19.2 meters (excluding engines) masses only 35.8 tons, with a burn time of 1:40. This is obviously much too little, and R-7 recreations made with ROT tanks will be underweight and underperform.

For reference, a tank or roughly the same dimensions constructed of proc tanks masses 48 tons with a burn time of 2:12, indicating it is physically possible to fit the required fuel load in the given volume.

The ROT booster tank with the given specifications has a volume of 33.5 kL. Matching the mass given by astronautix requires a 39.04 kL tank, while matching the burn time requires a 39.84 kL tank, indicating ROT is underestimating tank volume by 18-19%. I suspect the tank butt calculations may be behaving poorly when applied to conical tanks.

**Comment by Capkirk123** [comment]
Based on the Soyuz-ST users guide and Russian Space Web, the propellant mass in a Soyuz booster is estimated to 39.6 tons. This suggests the booster tank needs to have a volume of 39.14 kL, requiring the volume of the existing ROT booster tank to be increased by 1.1684 times.

**Comment by pap1723** [comment]
Fixed with https://github.com/KSP-RO/ROTanks/commit/1997056270894b10d0c0de54e686674eae978416
